version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/jbelmont/algorithms-workshop
    steps:
      - checkout
      - run:
          name: "Test Code and Run Coverage"
          command: make ci-test